apiVersion: v1
kind: Service
metadata:
  name: desafio-pantore-db-svc
  namespace: desafio-pantore
spec:
  selector:
    app: desafio-pantore-db
  ports:
    - protocol: TCP
      port: 5432
      targetPort: 5432
  type: ClusterIP
