apiVersion: v1
kind: Service
metadata:
  name: desafio-pantore-svc
  namespace: desafio-pantore
spec:
  selector:
    app: desafio-pantore
  ports:
    - protocol: TCP
      port: 8080
      targetPort: 8080
  type: LoadBalancer
